api_platform:
    title: Hello API Platform
    use_symfony_listeners: true
    version: 1.0.0
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        multipart: [ 'multipart/form-data' ]

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
